package com.example.demo.panda_channel.db.histroy;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "MY_HISTROY".
 */
public class MyHistroy {

    private Long id;
    private String img;
    private String title;
    private String date;
    private String moviepath;
    private boolean checkbox;
    private boolean flag;

    public MyHistroy() {
    }

    public MyHistroy(Long id, String img, String title, String date, String moviepath, Boolean checkbox, Boolean flag) {
        this.id = id;
        this.img = img;
        this.title = title;
        this.date = date;
        this.moviepath = moviepath;
        this.checkbox = checkbox;
        this.flag = flag;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getImg() {
        return img;
    }

    public void setImg(String img) {
        this.img = img;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getDate() {
        return date;
    }

    public void setDate(String date) {
        this.date = date;
    }

    public String getMoviepath() {
        return moviepath;
    }

    public void setMoviepath(String moviepath) {
        this.moviepath = moviepath;
    }

    public boolean isCheckbox() {
        return checkbox;
    }

    public void setCheckbox(boolean checkbox) {
        this.checkbox = checkbox;
    }

    public boolean isFlag() {
        return flag;
    }

    public void setFlag(boolean flag) {
        this.flag = flag;
    }


}
